
--Actualizacion de los productos
UPDATE fnica.ARTICULO SET USA_LOTES = 'S',MIN_VIDA_COMPRA = 120,MIN_VIDA_CONSUMO = 300,MIN_VIDA_VENTA = 400,VIDA_UTIL_PROM = 250
WHERE ARTICULO='Fe00012'


SELECT * FROM fnica.LOTE


SELECT USA_LOTES,LOTE_MULTIPLO,OBLIGA_CUARENTENA, MIN_VIDA_COMPRA,
       MIN_VIDA_CONSUMO, MIN_VIDA_VENTA, VIDA_UTIL_PROM, DIAS_CUARENTENA,
       LOTE_MULTIPLO, UTILIZADO_MANUFACT, MANUFACTURADOR
  FROM fnica.ARTICULO WHERE ARTICULO='JEM0001'  
  
  
---Cada vez que se haga un ingreso hay que registratrlo en esta db  
SELECT 	ing.secuencia_lote,   ing.fecha_entrada,ing.cantidad_ingresada  
FROM FNICA.ingresos_lote ing (NOLOCK)  WHERE ing.lote = 'NEWLOT'
AND ing.articulo = 'FE00012' ORDER BY 1 ASC
  
SELECT * FROM FNICA.EXISTENCIA_LOTE WHERE ARTICULO='fE00012'


SELECT * FROM FNICA.ingresos_lote  
  
  SELECT * FROM fnica.LINEA_DOC_INV WHERE DOCUMENTO_INV='COMP-001041'