INSERT INTO fnica.LOTE(LOTE, ARTICULO, PROVEEDOR, LOTE_DEL_PROVEEDOR,
            FECHA_ENTRADA, FECHA_VENCIMIENTO, FECHA_CUARENTENA, CANTIDAD_INGRESADA,
            ESTADO, TIPO_INGRESO, NOTAS, ULTIMO_INGRESO)
SELECT LoteProveedor,Articulo,Proveedor,loteproveedor,FechaIngreso, FechaVence,GETDATE(),0,'A','E','',0
  FROM fnica.invLOTE WHERE Articulo='FE00012' 

SELECT * FROM fnica.invEXISTENCIALOTE WHERE Articulo='Fe00012' AND Bodega='AL01'

insert into fnica.EXISTENCIA_LOTE(BODEGA, ARTICULO, LOCALIZACION, LOTE,
            CANT_DISPONIBLE, CANT_RESERVADA, CANT_NO_APROBADA, CANT_VENCIDA,
            CANT_REMITIDA)
SELECT A.Bodega, A.Articulo,'ND',B.LoteProveedor,A.Existencia,0,0,0,0
  FROM fnica.invEXISTENCIALOTE A
inner join fnica.invlote B ON B.IDLote = A.IDLote AND B.Articulo = A.Articulo
 WHERE A.Articulo='Fe00012' AND A.Bodega='AL01'     
 
 SELECT * FROM fnica.EXISTENCIA_LOTE
 update fnica.EXISTENCIA_LOTE  SET CANT_DISPONIBLE = 330.86 WHERE LOTE='FE0001220140218'      
 SELECT * FROM fnica.EXISTENCIA_BODEGA WHERE ARTICULO='Fe00012' AND BODEGA='AL01'